### ISSUE TITLE
Automatically write the latest numbers to a channel

### ISSUE THREAD

**Issue by VocalZero** [GermanyCovid/germanycovid-discordbot#4]
### Describe your idea to us
The bot should automatically write the latest numbers from a county or state to a channel. If possible, the bot should always edit its previously sent message in the channel.

### Additional context
The suggestion comes from tomgewiese on Twitter.
https://twitter.com/tomgewiese/status/1387635078482780163

**Comment by HappyFr1tz** [comment]
For the planning of this update - @VocalZero 
I would say to make it so that you can execute by command with admin rights that in a channel permanently the data update automatically. So for example for Duisburg. Then I say for example per !permdistricts duisburg #channel that there permanently these data aktualiesieren. So new infections, deaths, incidence, recovered and the other things. Here, however, the status is still added. Since the data do not always update at 0:00, I would say that you then specify the time (CEST) and if necessary between 0:00 and 7:00 say that the data may not yet have been updated? One could introduce such a command of course also for the federal states. However, in order not to shoot our server out of life, I would say that we limit it per server to one or two, and these update themselves hourly?

**Comment by VocalZero** [comment]
Will be implemented in v2.
